apiVersion: v1
kind: Service
metadata:
  name: phpma-service
  annotations:
    metallb.universe.tf/allow-shared-ip: "sharing key"
  labels:
    app: phpma-service
spec:
  selector:
    app: phpma-pod
  type: LoadBalancer
  loadBalancerIP: 172.17.0.2
  ports:
  - port: 5000
    name: phpma-service-port
    targetPort: phpma-cont-port
    protocol: TCP
    nodePort: 5000

--- 

apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
  labels:
    app: phpma-deployment
spec:
  selector:
    matchLabels:
      app: phpma-pod
  template:
    metadata:
      labels:
        app: phpma-pod
    spec:
      containers:
      - name: phpmyadmin
        image: phpmyadmin_image
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
          name: phpma-cont-port
        env:
        - name: __DB_HOST__
          valueFrom:
            configMapKeyRef:
              name: wp-phpma-configmap
              key: wordpress-db-host
        - name: __DB_NAME__
          valueFrom:
            secretKeyRef:
              name: wp-mysql-phpma-secret
              key: wordpress-db-name
        - name: __DB_USERNAME__
          valueFrom:
            secretKeyRef:
              name: wp-mysql-phpma-secret
              key: mysql-db-user
        - name: __DB_PASSWORD__
          valueFrom:
            secretKeyRef:
              name: wp-mysql-phpma-secret
              key: mysql-db-passwd

