apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  annotations:
    metallb.universe.tf/allow-shared-ip: "sharing key"
  labels:
    app: grafana-service
spec:
  selector:
    app: grafana-pod
  type: LoadBalancer
  loadBalancerIP: ${CLUSTER_EXTERNAL_IP}
  ports:
  - port: 3000
    name: graf-svc-port
    targetPort: graf-cont-port
    protocol: TCP
    nodePort: 3000

--- 

apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  labels:
    app: grafana-deployment
spec:
  selector:
    matchLabels:
      app: grafana-pod
  template:
    metadata:
      labels:
        app: grafana-pod
    spec:
      containers:
      - name: grafana
        image: grafana_image
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
          name: graf-cont-port
        envFrom:
          - secretRef:
              name: telegraf-secrets
        envFrom:
          - secretRef:
              name: grafana-secrets
        envFrom:
          - configMapRef:
              name: grafana-configmap
