apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      # the range notation is dropped for a single ip notation.
      #- 172.17.0.2-172.17.0.255
      - ${CLUSTER_EXTERNAL_IP}/32
