apiVersion: v1
kind: Service
metadata:
  name: nginx-deployment
spec:
  selector:
    app: nginx-deployment
  #note: use the following if you dont need to use the ingress, straight access.
  #type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 80
      #note: by default target port is set as the same as the port...
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
